/*
 * This source file was generated by the Gradle 'init' task
 */
package megges.kiddyquest.dpc

class DeviceAdminReceiver {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    println(App().greeting)
}
